import { useMemo, useRef, useState } from 'react';
import { ZoomIn, ZoomOut, LocateFixed } from 'lucide-react';
import type { Player, Site } from '../../types/game';

const icons: Record<string, string> = { yungang: 'icon_node_yungang.png', huayan_temple: 'icon_node_huayan_temple.png', shanhua_temple: 'icon_node_shanhua_temple.png', wall_pass: 'icon_node_wall_pass.png', trade_post: 'icon_node_trade_post.png', pingcheng_ruins: 'icon_node_pingcheng_ruins.png' };
export function HeritageNetwork({ sites, metaSites, active, focusedId, onFocus }: { sites: Record<string, Site>; metaSites: Record<string, Site>; active: Player; focusedId: string | null; onFocus: (id: string) => void }) {
  const [zoom, setZoom] = useState(1); const [pan, setPan] = useState({ x: 0, y: 0 }); const drag = useRef<{ x: number; y: number } | null>(null); const nodeList = Object.values(sites); const edges = useMemo(() => Object.values(metaSites).flatMap(site => (site.connections || []).map(to => `${site.id}:${to}`)), [metaSites]);
  function move(event: React.PointerEvent) { if (!drag.current) return; setPan({ x: event.clientX - drag.current.x, y: event.clientY - drag.current.y }); }
  return <div className="network-frame" onPointerMove={move} onPointerUp={() => { drag.current = null; }} onPointerLeave={() => { drag.current = null; }}><div className="network-tools"><button onClick={() => setZoom(value => Math.min(1.7, value + .15))} title="放大"><ZoomIn /></button><button onClick={() => setZoom(value => Math.max(.75, value - .15))} title="缩小"><ZoomOut /></button><button onClick={() => { setZoom(1); setPan({ x: 0, y: 0 }); }} title="重置地图"><LocateFixed /></button></div><svg viewBox="0 0 100 100" role="img" aria-label="云冈遗产节点网络" style={{ transform: `translate(${pan.x / 8}px, ${pan.y / 8}px) scale(${zoom})` }}><defs><filter id="glow"><feGaussianBlur stdDeviation="1.4" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs><image href="/ui-assets/01_buddha_relief_medallion.webp" x="30" y="30" width="40" height="40" opacity=".52" /><g className="network-lines">{edges.map(edge => { const [from, to] = edge.split(':'); const a = metaSites[from]; const b = metaSites[to]; if (!a || !b) return null; const highlighted = focusedId === from || focusedId === to || active.location === from || active.location === to; return <line key={edge} x1={a.x || 50} y1={a.y || 50} x2={b.x || 50} y2={b.y || 50} className={highlighted ? 'highlighted' : ''} />; })}</g></svg><div className="map-nodes" style={{ transform: `translate(${pan.x / 8}px, ${pan.y / 8}px) scale(${zoom})` }}>{nodeList.map(site => { const meta = metaSites[site.id] || site; const current = active.location === site.id; const available = site.status !== 'closed'; return <button key={site.id} className={`site-node ${current ? 'current' : ''} ${focusedId === site.id ? 'focused' : ''} ${available ? 'reachable' : 'closed'}`} style={{ left: `${meta.x || 50}%`, top: `${meta.y || 50}%` }} onClick={() => onFocus(site.id)} aria-label={`${meta.name || site.id}，${site.status}`}><span className="node-ring" /><img src={`/ui-assets/${icons[site.id] || 'icon_node_yungang.png'}`} alt="" /><b>{meta.name || site.id}</b><small>{site.status === 'closed' ? '已关闭' : current ? '当前位置' : `${site.damage}/${site.max_damage} 损伤`}</small></button>; })}</div><div className="network-corner">光照关系图 <span>拖动查看 · 点击节点聚焦</span></div></div>;
}
