import { useEffect, useState } from 'react';
import { Archive, ChevronDown, CircleAlert, Clock3, Map as MapIcon, Send, ShieldCheck, Sparkles, Target, Users, X } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Navigate, useParams } from 'react-router-dom';
import { ApiError, api } from '../../shared/api/client';
import type { Action, ActionOption, ActionType, ContentCard, ContentEvent, GameState, Meta, Site, Task } from '../../types/game';
import { HeritageNetwork } from '../../widgets/heritage-network/HeritageNetwork';
import { CommandDock } from '../../widgets/game/CommandDock';
import { ScenarioHeader } from '../../widgets/game/ScenarioHeader';
import { SiteInspector } from '../../widgets/game/SiteInspector';
import { ActionTargetGuide } from '../../widgets/game/JourneyGuide';
import { RoundSummary } from '../../widgets/game/RoundSummary';
import { ActionPreview } from '../../widgets/game/ActionPreview';
import { TutorialGuide } from '../../widgets/game/TutorialGuide';
import { SeatHandoff } from '../../widgets/game/SeatHandoff';
import { useDialogFocus } from '../../widgets/game/useDialogFocus';
import { actionFeedback, actionLabels, actionModeLabel, findCardAction, localizeActionError, localizeActionText, localizeTimelineMessage, optionAction, previewDeltaText, roleBadgeAsset, type ActionMode } from '../../widgets/game/gameUi';
import { useRoomEvents } from '../../shared/useRoomEvents';
import { getRoomToken } from '../../shared/roomToken';
import { JourneyTimeline } from '../../widgets/game/JourneyTimeline';
import { GameViewport } from '../../widgets/game/GameViewport';
import { StateChangeList } from '../../widgets/game/StateChangeList';
import { StrategyCardDialog } from '../../widgets/game/StrategyCardDialog';
import { assetUrl } from '../../shared/assetUrl';
import '../../styles/experience.css';
import '../../styles/tutorial.css';
import '../../styles/interface-scale.css';
import '../../styles/handoff.css';
import '../../styles/fullscreen-map.css';


export function GamePage() {
  const { sessionId = '', roomId = '' } = useParams();
  const queryClient = useQueryClient();
  const [focus, setFocus] = useState<string | null>(null);
  const [card, setCard] = useState<string | null>(null);
  const [strategyOption, setStrategyOption] = useState<ActionOption | null>(null);
  const [preview, setPreview] = useState<Action | null>(null);
  const [actionMode, setActionMode] = useState<ActionMode>(null);
  const [mobileView, setMobileView] = useState<'map' | 'mission' | 'hand'>('map');
  const [toasts, setToasts] = useState<Array<{ id: string; text: string }>>([]);
  const [inspectorOpen, setInspectorOpen] = useState(true);
  const [tutorialOpen, setTutorialOpen] = useState(false);
  const [handoffName, setHandoffName] = useState<string | null>(null);
  const [selectedOption, setSelectedOption] = useState<ActionOption | null>(null);
  const [completedTask, setCompletedTask] = useState<{ task: Task; siteName: string; changes: Array<{ label?: string; before?: string | number | null; after?: string | number | null; delta?: number | null }> } | null>(null);
  const [lastActionType, setLastActionType] = useState<ActionType | null>(null);
  const [roomToken] = useState(() => roomId ? getRoomToken(roomId) : '');
  const [roomEventState, setRoomEventState] = useState<'connected' | 'retrying' | 'ended' | 'unauthorized'>('connected');
  const enqueueToast = (text: string) => { const id = crypto.randomUUID(); setToasts(items => [...items.slice(-3), { id, text }]); window.setTimeout(() => setToasts(items => items.filter(item => item.id !== id)), 4800); };
  const gameQuery = useQuery<GameState>({ queryKey: [roomId ? 'room-game' : 'game', roomId || sessionId, roomToken], queryFn: () => roomId ? api.roomGame(roomId, roomToken) : api.game(sessionId), refetchOnWindowFocus: false, refetchInterval: roomId ? 2500 : false });
  useRoomEvents({ roomId, token: roomToken, onRevision: () => { void queryClient.invalidateQueries({ queryKey: ['room-game', roomId, roomToken] }); }, onState: setRoomEventState });
  const metaQuery = useQuery<Meta>({ queryKey: ['meta'], queryFn: api.meta });
  const state = gameQuery.data;
  const actionOptions = state?.action_options || [];
  const legal = actionOptions.flatMap(option => option.targets.length ? option.targets.map(target => optionAction(option, target)) : [optionAction(option)]);
  const canAct = state?.viewer?.can_act ?? true;
  const mutation = useMutation({
    mutationFn: (action: Action) => roomId ? api.roomAction(roomId, roomToken, action, state?.revision || 0) : api.action(sessionId, action, state?.shared.active_player_id || '', state?.revision || 0),
    onSuccess: (data, action) => { setLastActionType(action.type); queryClient.setQueryData([roomId ? 'room-game' : 'game', roomId || sessionId, roomToken], data); setPreview(null); setSelectedOption(null); setActionMode(null); if (action.type === 'move' && action.target_id) { setFocus(action.target_id); setInspectorOpen(true); } if (action.type === 'choose_intervention') { const newlyCompleted = Object.values(data.tasks).find(nextTask => nextTask.completed && !state?.tasks[nextTask.id || '']?.completed); if (newlyCompleted) { const completedSite = Object.values(data.sites).find(item => item.active_task_id === newlyCompleted.id); setCompletedTask({ task: newlyCompleted, siteName: completedSite?.id || '当前节点', changes: (data.feedback_events || []).flatMap(event => event.changes || []) }); } } if (data.viewer?.play_mode === 'local' && action.type === 'end_turn' && data.players[data.shared.active_player_id]) setHandoffName(data.players[data.shared.active_player_id].name); if (action.type === 'end_turn' && state?.shared.current_event_id !== data.shared.current_event_id && data.shared.current_event_id) { const settledName = currentEvent?.name || '上一轮事件'; const nextName = meta.events?.find(item => item.id === data.shared.current_event_id)?.name || '新的世界事件'; enqueueToast(`${settledName}已结算，${nextName}已揭示。`); } (data.feedback_events?.length ? data.feedback_events : [{ message: actionFeedback(action, state, data), changes: [] }]).forEach((event, index) => window.setTimeout(() => enqueueToast([event.message, ...(event.changes || []).map(change => `${change.label || '状态变化'} ${change.delta > 0 ? '+' : ''}${change.delta ?? ''}`)].filter(Boolean).join(' · ')), index * 180)); },
    onError: error => { if (error instanceof ApiError && error.status === 409) { const current = (error.payload as { detail?: { current_state?: GameState } })?.detail?.current_state; if (current) { queryClient.setQueryData([roomId ? 'room-game' : 'game', roomId || sessionId, roomToken], current); setActionMode(null); setSelectedOption(null); setPreview(null); enqueueToast('状态已同步，请重新选择行动。'); return; } } setActionMode(null); setSelectedOption(null); setPreview(null); enqueueToast(localizeActionError(error)); }
  });
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') { setActionMode(null); setSelectedOption(null); setCard(null); setPreview(null); } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, []);
  if (gameQuery.isLoading || metaQuery.isLoading) return <div className="state-screen"><span className="loading-orbit" /><p>正在读取遗产网络…</p></div>;
  if (gameQuery.isError || metaQuery.isError || !state || !metaQuery.data) return <div className="state-screen danger"><CircleAlert /><h1>旅程暂时无法打开</h1><p>请检查本地服务后重新进入旅程。</p><button className="ghost-button" onClick={() => { void gameQuery.refetch(); void metaQuery.refetch(); }}>重新连接</button><button className="ghost-button" onClick={() => window.location.assign('/')}>返回首页</button></div>;
  if (state.shared.outcome) return <Navigate to={roomId ? `/room/${roomId}/result` : `/result/${state.session_id}`} replace />;

  const meta = metaQuery.data;
  const active = state.players[state.shared.active_player_id];
  const sites = Object.fromEntries(meta.sites.map(site => [site.id, site]));
  const cards = Object.fromEntries(meta.cards.map(item => [item.id, item]));
  const events = Object.fromEntries(meta.events.map(item => [item.id, item]));
  const roles = Object.fromEntries(meta.roles.map(item => [item.id, item]));
  const focused: Site = state.sites[focus || active.location] || state.sites[active.location] || Object.values(state.sites)[0];
  const focusedMeta = sites[focused.id] || focused;
  const task = focusedMeta.active_task_id ? state.tasks[focusedMeta.active_task_id] : undefined;
  const currentEvent = state.shared.current_event_id ? events[state.shared.current_event_id] : undefined;
  const eventTargetLabels = (state.shared.event_targets || []).map(id => sites[id]?.name || (state.routes?.[id] ? '选中路线' : '事件目标'));
  const targetIds = new Set((selectedOption?.type === actionMode ? selectedOption.targets : []).map(target => String(target.payload?.target_id || target.payload?.target_site_id || target.id)));
  const connection = mutation.isPending || gameQuery.isFetching || metaQuery.isFetching ? '同步中' : roomEventState === 'unauthorized' ? '席位失效' : roomEventState === 'retrying' ? '重连中' : roomEventState === 'ended' ? '重新连接' : '已连接';
  const run = (action?: Action) => { if (action && canAct && !mutation.isPending) mutation.mutate({ ...action, request_id: action.request_id || crypto.randomUUID() }); };
  const chooseOption = (option: ActionOption) => { if (!canAct || option.enabled === false) return; if (option.type === 'explore') { setSelectedOption(null); setActionMode('explore'); setInspectorOpen(true); return; } if (option.targets.length) { setSelectedOption(option); if (['move', 'restore', 'survey_route', 'restore_route', 'establish_connection'].includes(option.type)) { setActionMode(option.type as ActionMode); setFocus(active.location); } else setActionMode(null); return; } const action = optionAction(option); if (option.type === 'end_turn') { const weathering = state.shared.weathering_track ?? state.shared.threat ?? 0; const warnings = [active.ap > 0 ? `你还有 ${active.ap} 点行动力未使用` : '', state.shared.current_event_id ? '当前事件将在回合结束时结算' : '', weathering >= Math.max(0, (state.shared.weathering_limit || 5) - 1) ? '风化压力已经接近上限' : ''].filter(Boolean); setPreview({ ...action, description: warnings.length ? `${warnings.join('；')}。确认结束后将进入事件结算。` : '确认结束本角色行动并进入事件结算。' }); return; } if (['use_skill', 'use_node_ability', 'use_upgrade', 'end_planning', 'prepare'].includes(option.type)) setPreview(action); else run(action); };
  const chooseAction = (type: ActionType) => { const option = state.action_options?.find(item => item.type === type && item.enabled !== false); if (option) chooseOption(option); };
  const selectAction = (action: Action) => { setActionMode(null); setSelectedOption(null); setPreview(action); };
  const selectNode = (id: string) => { const target = mapActionMode && selectedOption?.type === actionMode ? selectedOption.targets.find(item => { const payload = item.payload || {}; return item.id === id || payload.target_id === id || payload.target_site_id === id || payload.route_id === id; }) : undefined; if (target && selectedOption) { selectAction(optionAction(selectedOption, target)); return; } setFocus(id); setInspectorOpen(true); };
  const mapActionMode = actionMode && ['move', 'restore', 'survey_route', 'restore_route', 'establish_connection'].includes(actionMode) ? actionMode as Extract<ActionType, 'move' | 'restore' | 'survey_route' | 'restore_route' | 'establish_connection'> : null;
  const selectExploreCard = (id: string) => { const option = state.action_options?.find(item => item.type === 'explore' && item.targets.some(target => target.payload?.card_id === id)); const target = option?.targets.find(item => item.payload?.card_id === id); if (option && target) selectAction(optionAction(option, target)); };
  const selectInterpretation = (cardId: string, relation: 'support' | 'conflict' | 'pending') => { const action = legal.find(item => item.type === 'interpret_evidence' && item.card_id === cardId && item.target_id === relation); if (action) selectAction(action); };
  const formInterpretation = () => { const action = legal.find(item => item.type === 'form_interpretation'); if (action) selectAction(action); };
  const chooseIntervention = (choice: 'act_now' | 'minimal' | 'record') => { const action = legal.find(item => item.type === 'choose_intervention' && item.target_id === choice); if (action) selectAction(action); };
  const pendingAction = (action: Action) => state.pending_choice?.kind === 'action_card' ? selectAction(action) : run(action);

  const timelineEvents = (state.shared.journal?.length ? state.shared.journal : state.shared.log.map((message, index) => ({ id: `legacy-${index}`, round: state.shared.turn, type: 'action', message, effects: [], created_at: '', player_id: state.shared.active_player_id }))).map(entry => ({ ...entry, player_name: entry.player_id ? state.players[entry.player_id]?.name : undefined, message: localizeTimelineMessage(entry.message, { sites, routes: state.routes || {}, projects: state.projects || {}, players: state.players }) }));
  const hasExplicitFocus = focus !== null;
  return <GameViewport><div className="game-shell game-viewport"><ScenarioHeader state={state} scenarioName={meta.scenarios?.find(item => item.id === (state.scenario_id || state.shared.scenario_id))?.name || '未命名旅程'} connection={connection} /><div className="mobile-tabs" role="tablist" aria-label="游戏内容"><button role="tab" aria-selected={mobileView === 'map'} aria-controls="mobile-map-panel" className={mobileView === 'map' ? 'active' : ''} onClick={() => setMobileView('map')}><MapIcon size={16} />地图</button><button role="tab" aria-selected={mobileView === 'mission'} aria-controls="mobile-mission-panel" className={mobileView === 'mission' ? 'active' : ''} onClick={() => setMobileView('mission')}><Target size={16} />地点</button><button role="tab" aria-selected={mobileView === 'hand'} aria-controls="mobile-hand-panel" className={mobileView === 'hand' ? 'active' : ''} onClick={() => setMobileView('hand')}><Archive size={16} />手牌</button></div><main className={`game-grid ${inspectorOpen ? '' : 'inspector-collapsed'}`}>
    <aside className={`roster-column ${mobileView !== 'map' ? 'mobile-hidden' : ''}`} id="mobile-map-panel"><section className="roster"><div className="section-label"><Users size={14} />共同旅伴</div>{state.shared.player_order.map(id => { const player = state.players[id]; const role = roles[player.role_id]; return <button key={id} className={`roster-row ${id === state.shared.active_player_id ? 'active' : ''}`} onClick={() => setFocus(player.location)}><img src={assetUrl(roleBadgeAsset(player.role_id, role?.icon_asset))} alt="" /><span><b>{player.name}</b><small>{role?.name || player.role_id} · {sites[player.location]?.name || player.location}</small></span><strong>{player.ap} <small>AP</small></strong></button>; })}</section><section className="current-player"><div className="section-label">当前行动者</div><h2>{active.name}</h2><p>{roles[active.role_id]?.name || active.role_id}</p><div className="player-resources"><span><b>{active.ap}</b><small>行动点</small></span><span><b>{active.influence}</b><small>个人声望</small></span><span><b>{active.supplies || 0}</b><small>个人补给</small></span></div></section><CommandDock state={state} active={active} cards={cards} legal={legal} actionOptions={actionOptions} actionMode={actionMode} actionLabels={actionLabels} mutationPending={mutation.isPending} canAct={canAct} onRun={run} onChooseOption={chooseOption} onCancel={() => { setActionMode(null); setSelectedOption(null); }} onCard={setCard} /></aside>
    <section className={`stage-column ${mobileView !== 'map' ? 'mobile-hidden' : ''}`}><RoundSummary state={state} sites={sites} /><div className="stage-heading"><div><span className="eyebrow">石窟光谱 · 遗产网络</span><h1>遗产节点网络</h1></div><span className="turn-badge"><Clock3 size={14} />回合 {state.shared.turn}</span></div><div className="network-stage">{actionMode && <div className="mode-strip" role="status" aria-live="polite">正在选择{actionModeLabel(actionMode)}目标 · 已显示 {targetIds.size} 个合法目标 · <button onClick={() => { setActionMode(null); setSelectedOption(null); }}>取消选择</button></div>}<ActionTargetGuide mode={actionMode === 'explore' ? null : actionMode} actions={(selectedOption?.type === actionMode ? selectedOption.targets.map(target => optionAction(selectedOption, target)) : [])} sites={sites} routes={state.routes} cards={cards} onRun={selectAction} onCancel={() => { setActionMode(null); setSelectedOption(null); }} /><HeritageNetwork sites={state.sites} metaSites={sites} regions={meta.regions} routes={state.routes} players={Object.values(state.players)} active={active} focusedId={focus} reachableIds={targetIds} actionMode={mapActionMode} onFocus={selectNode} /></div><div className="stage-caption" data-focused={hasExplicitFocus ? 'true' : 'false'}><div className="scene-thumb"><img src={assetUrl(focusedMeta.scene_asset, 'generated/scene_yungang_day.png')} alt="当前聚焦地点场景" /></div><div><span className="eyebrow">当前聚焦</span><h2>{focusedMeta.name || focused.id}</h2><p>{focusedMeta.summary || '等待探索后显示节点的文化摘要。'}</p></div><button className="focus-clear" onClick={() => { setFocus(null); setActionMode(null); setSelectedOption(null); }} aria-label="取消聚焦"><X size={16} /></button></div></section>
     <SiteInspector state={state} meta={meta} site={focusedMeta} task={task} event={currentEvent} cards={cards} legal={legal} actionMode={actionMode} collapsed={!inspectorOpen} onCollapsedChange={setInspectorOpen} onExplore={selectExploreCard} onSelectAction={chooseAction} onInterpret={selectInterpretation} onFormInterpretation={formInterpretation} onChooseIntervention={chooseIntervention} className={mobileView !== 'mission' ? 'mobile-hidden' : ''} /></main><MobileHandPanel id="mobile-hand-panel" hidden={mobileView !== 'hand'} active={active} cards={cards} actionOptions={actionOptions} onCard={setCard} onChooseOption={chooseOption} onStrategy={setStrategyOption} /><JourneyTimeline entries={timelineEvents} />{toasts.map(item => <div key={item.id} className="toast toast-queue" role="status">{item.text}</div>)}{completedTask && <TaskCompleteDialog task={completedTask.task} siteName={sites[completedTask.siteName]?.name || focusedMeta.name || '当前节点'} changes={completedTask.changes} onClose={() => setCompletedTask(null)} />}{card && <CardDialog id={card} item={cards[card]} action={findCardAction(legal, 'play_card', card)} onClose={() => setCard(null)} onUse={action => { setCard(null); if (action) setPreview(action); }} />}{state.pending_choice && <ChoiceDialog state={state} event={currentEvent} disabled={mutation.isPending} onChoose={pendingAction} />}{selectedOption && !mapActionMode && <ActionTargetDialog option={selectedOption} disabled={mutation.isPending} onChoose={target => selectAction(optionAction(selectedOption, target))} onCancel={() => { setActionMode(null); setSelectedOption(null); }} />}{preview && <ActionPreview action={preview} sites={sites} routes={state.routes} cards={cards} players={state.players} isPending={mutation.isPending} onConfirm={() => run(preview)} onCancel={() => setPreview(null)} />}<TutorialGuide open={tutorialOpen} onOpenChange={setTutorialOpen} state={state} actionOptions={actionOptions} triggerAction={lastActionType} />{handoffName && <SeatHandoff name={handoffName} onContinue={() => setHandoffName(null)} />}{strategyOption && <StrategyCardDialog option={strategyOption} disabled={mutation.isPending} onClose={() => setStrategyOption(null)} onConfirm={option => { setStrategyOption(null); chooseOption(option); }} />}</div></GameViewport>;
}

function TaskCompleteDialog({ task, siteName, changes, onClose }: { task: Task; siteName: string; changes: Array<{ label?: string; before?: string | number | null; after?: string | number | null; delta?: number | null }>; onClose: () => void }) {
  const ref = useDialogFocus();
  return <div className="dialog-backdrop"><section ref={ref} className="dialog task-complete-dialog" role="dialog" aria-modal="true" aria-labelledby="task-complete-title"><span className="eyebrow"><ShieldCheck size={15} />互证完成</span><h2 id="task-complete-title">{task.name}</h2><p>{siteName} 的线索已彼此照见。你们已经完成一段可被共同引用的文化解释。</p><div className="task-complete-reward"><b>本次改变</b>{changes.length ? <StateChangeList changes={changes} /> : <span>解释已写入遗产网络，地图与旅程记录已更新。</span>}<span>对应领域印记已加入图卷</span></div><button className="primary-cta" onClick={onClose}>继续旅程</button></section></div>;
}
function MobileHandPanel({ id, hidden, active, cards, actionOptions, onCard, onChooseOption, onStrategy }: { id: string; hidden: boolean; active: GameState['players'][string]; cards: Record<string, ContentCard>; actionOptions: ActionOption[]; onCard: (id: string) => void; onChooseOption: (option: ActionOption) => void; onStrategy: (option: ActionOption) => void }) {
  return <section id={id} className={`mobile-hand-panel ${hidden ? 'mobile-hidden' : ''}`} aria-label="手牌与角色能力"><div className="section-label"><Archive size={15} />文化牌 <b>{active.hand.length} / 3</b></div><div className="mobile-hand-grid">{active.hand.map(id => <button key={id} className="hand-card" onClick={() => onCard(id)}><img src={assetUrl(cards[id]?.icon_asset)} alt="" /><b>{cards[id]?.name || id}</b><small>{cards[id]?.strategic_role || '打开查看这件文化证据'}</small></button>)}</div>{active.action_hand?.length ? <><div className="section-label"><Sparkles size={15} />策略牌</div><div className="mobile-hand-grid">{active.action_hand.map(id => { const option = actionOptions.find(item => item.type === 'use_action_card' && item.id.endsWith(`:${id}`)); return <button key={id} className="hand-card strategy-card" disabled={!option || option.enabled === false} onClick={() => option && onStrategy(option)}><img src={assetUrl('icon_card_scroll.png')} alt="" /><b>{option?.label || '策略牌'}</b><small>{option?.description || '查看策略牌效果'}</small></button>; })}</div></> : null}<div className="hand-help">点击文化牌查看详情，策略牌先选择其目标再确认结算。</div></section>;
}

function ActionTargetDialog({ option, disabled, onChoose, onCancel }: { option: ActionOption; disabled: boolean; onChoose: (target: ActionOption['targets'][number]) => void; onCancel: () => void }) {
  const ref = useDialogFocus(); return <div className="dialog-backdrop"><section ref={ref} className="dialog choice-dialog action-target-dialog" role="dialog" aria-modal="true" aria-labelledby="action-target-title" aria-describedby="action-target-description"><button className="dialog-close" disabled={disabled} onClick={onCancel} aria-label="取消目标选择"><X /></button><span className="eyebrow">行动目标</span><h2 id="action-target-title">{localizeActionText(option.label)}</h2><p id="action-target-description">{localizeActionText(option.confirmation || option.description || '选择一个合法目标后继续。')}</p><div className="choice-list">{option.targets.map(target => <button className="choice-option" key={target.id} disabled={disabled} onClick={() => onChoose(target)}><span><b>{localizeActionText(target.label)}</b><small>{previewDeltaText(target.preview_delta, `${option.cost?.ap || 0} 点行动力`)}</small></span><ChevronDown size={16} /></button>)}</div><button className="ghost-button" disabled={disabled} onClick={onCancel}>返回浏览</button></section></div>;
}

function CardDialog({ id, item, action, onClose, onUse }: { id: string; item?: ContentCard; action?: Action; onClose: () => void; onUse: (action?: Action) => void }) { const ref = useDialogFocus(); return <div className="dialog-backdrop"><section ref={ref} className="dialog card-dialog" role="dialog" aria-modal="true" aria-labelledby="card-dialog-title"><button className="dialog-close" onClick={onClose} aria-label="关闭"><X /></button><img className="dialog-card-art" src={assetUrl(item?.icon_asset)} alt="" /><span className="eyebrow">文化证据</span><h2 id="card-dialog-title">{item?.name || id}</h2><p>{item?.description || item?.summary || '一份等待被理解并投入合适地点的文化记录。'}</p><div className="card-how-to-use"><b>怎么用</b><span>带回当前节点的研究台，选择它是“支持”“冲突”还是“待确认”。它会消耗 1 AP，并推进对应的领域、来源或组合条件。</span></div>{item?.combo_name && <p className="card-combo"><b>{item.combo_name}</b> · {item.combo_reward_text || item.instant_use_text}</p>}<button className="primary-cta" disabled={!action} onClick={() => onUse(action)}>{action ? '查看行动后果' : '当前不可使用'}</button></section></div>; }
function ChoiceDialog({ state, event, disabled = false, onChoose }: { state: GameState; event?: ContentEvent; disabled?: boolean; onChoose: (action: Action) => void }) {
  const isEvent = state.pending_choice?.kind === 'event';
  if (state.pending_choice?.kind === 'role_upgrade') return <RoleUpgradeDialog state={state} disabled={disabled} onChoose={onChoose} />;
  const ref = useDialogFocus();
  const choices = (state.action_options || []).flatMap(option => option.targets.length ? option.targets.map(target => optionAction(option, target)) : [optionAction(option)]);
  return <div className="dialog-backdrop"><section ref={ref} className="dialog choice-dialog" role="dialog" aria-modal="true" aria-labelledby="choice-dialog-title">
    <span className="eyebrow">{isEvent ? '世界事件 · 需要回应' : '共同决定'}</span>
    <h2 id="choice-dialog-title">{event?.name || (isEvent ? '线路正在等待回应' : '从市场中选择一件证据')}</h2>
    <p>{event?.forecast_text || event?.description || '你的选择会立即改变本回合的风险与资源。'}</p>
    {isEvent && state.shared.event_targets?.length ? <div className="choice-hint"><b>已锁定影响范围</b><span>{state.shared.event_targets.length} 个目标已由本局种子确定，选择会改变这些目标的结果。</span></div> : null}
    {event?.mitigation_hint && <div className="choice-hint"><b>应对建议</b><span>{event.mitigation_hint}</span></div>}
    <div className="choice-list">{choices.map((action, index) => <button disabled={disabled} key={`${action.type}-${index}`} onClick={() => onChoose(action)}>
      <span><b>{localizeActionText(action.label)}</b><small>{disabled ? '正在同步回应…' : localizeActionText(action.description) || '确认后查看实际变化'}</small>{<em>{previewDeltaText(action.preview_delta, action.cost ? `消耗 ${action.cost} AP` : '确认后结算')}</em>}</span><ChevronDown size={16} />
    </button>)}</div>
  </section></div>;
}
function RoleUpgradeDialog({ state, disabled = false, onChoose }: { state: GameState; disabled?: boolean; onChoose: (action: Action) => void }) { const options = (state.pending_choice?.options || []) as Array<{ id: string; name?: string; description?: string; trigger?: string; strategic_direction?: string; label?: string }>; const ref = useDialogFocus(); const choices = (state.action_options || []).flatMap(option => option.targets.length ? option.targets.map(target => optionAction(option, target)) : [optionAction(option)]); return <div className="dialog-backdrop"><section ref={ref} className="dialog role-upgrade-dialog" role="dialog" aria-modal="true" aria-labelledby="upgrade-dialog-title"><span className="eyebrow"><ShieldCheck size={15} />角色专长</span><h2 id="upgrade-dialog-title">为下一段旅程选择持续专长</h2><p>专长会保留到本局结束，并在描述的触发条件满足时生效。</p><div className="upgrade-options">{options.map(option => { const action = choices.find(item => item.upgrade_id === option.id); return <button key={option.id} disabled={disabled || !action} onClick={() => action && onChoose(action)}><span><b>{option.name || option.label || '角色专长'}</b><small>{disabled ? '正在同步选择…' : option.description || '选择后会持续改变该角色的行动方式。'}</small>{option.trigger && <i>触发：{option.trigger}</i>}</span><em>{option.strategic_direction || '长期协作'}</em></button>; })}</div></section></div>; }
