/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Game */
        post: operations["create_game_api_games_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_api_games__session_id__get"];
        put?: never;
        /**
         * Create Game With Id
         * @description Stable local-session creation endpoint used by demos, tests, and recovery flows.
         */
        post: operations["create_game_with_id_api_games__session_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{session_id}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Game */
        post: operations["join_game_api_games__session_id__players_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{session_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Game Action */
        post: operations["game_action_api_games__session_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Room */
        post: operations["create_room_api_rooms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Room */
        get: operations["get_room_api_rooms__room_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Room */
        post: operations["join_room_api_rooms__room_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ready Room */
        post: operations["ready_room_api_rooms__room_id__ready_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Role Room */
        post: operations["role_room_api_rooms__room_id__role_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Leave Room */
        post: operations["leave_room_api_rooms__room_id__leave_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Room */
        post: operations["pause_room_api_rooms__room_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Room */
        post: operations["resume_room_api_rooms__room_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Room */
        post: operations["start_room_api_rooms__room_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Room Game */
        get: operations["room_game_api_rooms__room_id__game_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Room Action */
        post: operations["room_action_api_rooms__room_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionRequest */
        ActionRequest: {
            /** Player Id */
            player_id: string;
            action: components["schemas"]["ActionType"];
            /** Expected Revision */
            expected_revision: number;
            /** Target Id */
            target_id?: string | null;
            /** Target Site Id */
            target_site_id?: string | null;
            /** Card Id */
            card_id?: string | null;
            /** Recipient Id */
            recipient_id?: string | null;
            /** Route Id */
            route_id?: string | null;
            /** Upgrade Id */
            upgrade_id?: string | null;
            /** Target Ids */
            target_ids?: string[] | null;
            /** Request Id */
            request_id?: string | null;
        };
        /**
         * ActionType
         * @enum {string}
         */
        ActionType: "move" | "explore" | "contribute" | "restore" | "exchange" | "use_skill" | "play_card" | "end_turn" | "resolve_event" | "select_market_card" | "discard" | "survey_route" | "restore_route" | "establish_connection" | "prepare" | "select_upgrade" | "plan" | "use_action_card" | "use_node_ability" | "use_upgrade" | "end_planning";
        /** CreateGameRequest */
        CreateGameRequest: {
            /** Player Ids */
            player_ids?: string[];
            /**
             * Difficulty Id
             * @default normal
             */
            difficulty_id: string;
            /**
             * Scenario Id
             * @default sand_and_stone
             */
            scenario_id: string;
            /** Seed */
            seed?: number | null;
            /** Daily Seed */
            daily_seed?: string | null;
        };
        /**
         * GameOutcome
         * @enum {string}
         */
        GameOutcome: "victory" | "defeat";
        /** GameState */
        GameState: {
            /**
             * Schema Version
             * @default 3
             */
            schema_version: number;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Session Id */
            session_id: string;
            /**
             * Mode
             * @default heritage_network
             */
            mode: string;
            /**
             * Difficulty Id
             * @default normal
             */
            difficulty_id: string;
            /** Players */
            players: {
                [key: string]: components["schemas"]["PlayerState"];
            };
            /** Sites */
            sites: {
                [key: string]: components["schemas"]["SiteState"];
            };
            /** Tasks */
            tasks?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            shared?: components["schemas"]["SharedState"];
            /** Decks */
            decks?: {
                [key: string]: string[];
            };
            /** Market */
            market?: string[];
            /** Pending Choice */
            pending_choice?: {
                [key: string]: unknown;
            } | null;
            /** Legal Actions */
            legal_actions?: {
                [key: string]: unknown;
            }[];
            /** Action Options */
            action_options?: {
                [key: string]: unknown;
            }[];
            /**
             * Scenario Id
             * @default sand_and_stone
             */
            scenario_id: string;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Rng State
             * @default 0
             */
            rng_state: number;
            /**
             * Rng Position
             * @default 0
             */
            rng_position: number;
            /** Migrated From Schema Version */
            migrated_from_schema_version?: number | null;
            /** Routes */
            routes?: {
                [key: string]: components["schemas"]["RouteState"];
            };
            /** Projects */
            projects?: {
                [key: string]: components["schemas"]["ProjectState"];
            };
            /** Objectives */
            objectives?: {
                [key: string]: components["schemas"]["ObjectiveState"];
            };
            score?: components["schemas"]["ScoreState"];
            /** Result */
            result?: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JoinGameRequest */
        JoinGameRequest: {
            /** Player Id */
            player_id: string;
            /** Role Id */
            role_id?: string | null;
        };
        /** ObjectiveState */
        ObjectiveState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Target
             * @default 1
             */
            target: number;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Completed
             * @default false
             */
            completed: boolean;
        };
        /** PlayerState */
        PlayerState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Role Id */
            role_id: string;
            /** Location */
            location: string;
            /**
             * Ap
             * @default 3
             */
            ap: number;
            /**
             * Max Ap
             * @default 3
             */
            max_ap: number;
            /**
             * Influence
             * @default 0
             */
            influence: number;
            /**
             * Durability
             * @default 3
             */
            durability: number;
            /** Hand */
            hand?: string[];
            /** Action Hand */
            action_hand?: string[];
            /** Flags */
            flags?: {
                [key: string]: unknown;
            };
            /**
             * Skill Used
             * @default false
             */
            skill_used: boolean;
            /**
             * Contributions
             * @default 0
             */
            contributions: number;
            /** Upgrades */
            upgrades?: string[];
        };
        /** ProjectState */
        ProjectState: {
            /** Id */
            id: string;
            /** Site Id */
            site_id: string;
            /** Name */
            name: string;
            /** Stages */
            stages?: {
                [key: string]: unknown;
            }[];
            /**
             * Stage Index
             * @default 0
             */
            stage_index: number;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Contributors */
            contributors?: string[];
            /** Stage Evidence */
            stage_evidence?: {
                [key: string]: unknown;
            }[];
            /** Completed Stages */
            completed_stages?: string[];
            /** Stage Progress */
            stage_progress?: {
                [key: string]: number;
            };
            /** Stage Contributors */
            stage_contributors?: {
                [key: string]: string[];
            };
            /** Available Choices */
            available_choices?: {
                [key: string]: unknown;
            }[];
        };
        /** RoomActionRequest */
        RoomActionRequest: {
            action: components["schemas"]["ActionType"];
            /** Expected Revision */
            expected_revision: number;
            /** Target Id */
            target_id?: string | null;
            /** Target Site Id */
            target_site_id?: string | null;
            /** Card Id */
            card_id?: string | null;
            /** Recipient Id */
            recipient_id?: string | null;
            /** Route Id */
            route_id?: string | null;
            /** Upgrade Id */
            upgrade_id?: string | null;
            /** Target Ids */
            target_ids?: string[] | null;
            /** Request Id */
            request_id?: string | null;
        };
        /** RoomCreateRequest */
        RoomCreateRequest: {
            /**
             * Play Mode
             * @default solo
             */
            play_mode: string;
            /**
             * Name
             * @default 同行者
             */
            name: string;
            /** Role Id */
            role_id?: string | null;
            /**
             * Scenario Id
             * @default sand_and_stone
             */
            scenario_id: string;
            /**
             * Difficulty Id
             * @default guided
             */
            difficulty_id: string;
            /** Seed */
            seed?: number | null;
            /**
             * Max Players
             * @default 4
             */
            max_players: number;
        };
        /** RoomJoinRequest */
        RoomJoinRequest: {
            /**
             * Name
             * @default 同行者
             */
            name: string;
            /** Role Id */
            role_id?: string | null;
        };
        /** RoomReadyRequest */
        RoomReadyRequest: {
            /**
             * Ready
             * @default true
             */
            ready: boolean;
        };
        /** RoomRoleRequest */
        RoomRoleRequest: {
            /** Role Id */
            role_id: string;
        };
        /** RouteState */
        RouteState: {
            /** Id */
            id: string;
            /** From Site */
            from_site: string;
            /** To Site */
            to_site: string;
            /**
             * Cost
             * @default 1
             */
            cost: number;
            /**
             * Status
             * @default open
             */
            status: string;
            /**
             * Risk
             * @default 0
             */
            risk: number;
            /**
             * Connection Level
             * @default 0
             */
            connection_level: number;
            /** Active Project Id */
            active_project_id?: string | null;
            /** Tags */
            tags?: string[];
        };
        /** ScoreState */
        ScoreState: {
            /**
             * Tasks
             * @default 0
             */
            tasks: number;
            /**
             * Routes
             * @default 0
             */
            routes: number;
            /**
             * Diversity
             * @default 0
             */
            diversity: number;
            /**
             * Protection
             * @default 0
             */
            protection: number;
            /**
             * Resources
             * @default 0
             */
            resources: number;
            /**
             * Efficiency
             * @default 0
             */
            efficiency: number;
            /**
             * Discovery
             * @default 0
             */
            discovery: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Grade
             * @default stone
             */
            grade: string;
        };
        /** SharedState */
        SharedState: {
            /**
             * Turn
             * @default 1
             */
            turn: number;
            /**
             * Max Rounds
             * @default 8
             */
            max_rounds: number;
            /**
             * Active Player Id
             * @default p1
             */
            active_player_id: string;
            /** Player Order */
            player_order?: string[];
            /**
             * Threat
             * @default 0
             */
            threat: number;
            /**
             * Influence
             * @default 0
             */
            influence: number;
            /**
             * Restoration Resource
             * @default 6
             */
            restoration_resource: number;
            /** Completed Domains */
            completed_domains?: string[];
            /** Current Event Id */
            current_event_id?: string | null;
            outcome?: components["schemas"]["GameOutcome"] | null;
            /** Outcome Reason */
            outcome_reason?: string | null;
            /**
             * Scenario Id
             * @default sand_and_stone
             */
            scenario_id: string;
            /**
             * Research Clues
             * @default 0
             */
            research_clues: number;
            /** Prepared Event Ids */
            prepared_event_ids?: string[];
            /**
             * Route Connection Score
             * @default 0
             */
            route_connection_score: number;
            /** Log */
            log?: string[];
            /** Planning Marks */
            planning_marks?: {
                [key: string]: {
                    [key: string]: string;
                }[];
            };
            /** Node Ability Uses */
            node_ability_uses?: string[];
            /**
             * Phase
             * @default player_action
             */
            phase: string;
            /**
             * Weathering Track
             * @default 0
             */
            weathering_track: number;
            /**
             * Weathering Limit
             * @default 5
             */
            weathering_limit: number;
            /** Effective Rules */
            effective_rules?: {
                [key: string]: unknown;
            };
            /**
             * Solo Mode
             * @default false
             */
            solo_mode: boolean;
            /** Controlled Character Ids */
            controlled_character_ids?: string[];
            /** Journal */
            journal?: {
                [key: string]: unknown;
            }[];
            /** Event Targets */
            event_targets?: string[];
            /** Event Instance */
            event_instance?: {
                [key: string]: unknown;
            };
            /** Event History */
            event_history?: {
                [key: string]: unknown;
            }[];
            /** Round Summary */
            round_summary?: {
                [key: string]: unknown;
            };
        };
        /** SiteState */
        SiteState: {
            /** Id */
            id: string;
            /**
             * Damage
             * @default 0
             */
            damage: number;
            /**
             * Max Damage
             * @default 3
             */
            max_damage: number;
            /**
             * Durability
             * @default 3
             */
            durability: number;
            /**
             * Max Durability
             * @default 3
             */
            max_durability: number;
            /** @default stable */
            status: components["schemas"]["SiteStatus"];
            /**
             * Influence
             * @default 0
             */
            influence: number;
            /**
             * Discovered
             * @default false
             */
            discovered: boolean;
            /** Domains */
            domains?: string[];
            /** Contributions */
            contributions?: {
                [key: string]: unknown;
            }[];
            /** Active Project Id */
            active_project_id?: string | null;
        };
        /**
         * SiteStatus
         * @enum {string}
         */
        SiteStatus: "stable" | "at_risk" | "closed";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_game_api_games_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_api_games__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_game_with_id_api_games__session_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_game_api_games__session_id__players_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    game_action_api_games__session_id__actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_room_api_rooms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_room_api_rooms__room_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_room_api_rooms__room_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomJoinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_room_api_rooms__room_id__ready_post: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomReadyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    role_room_api_rooms__room_id__role_post: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leave_room_api_rooms__room_id__leave_post: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_room_api_rooms__room_id__pause_post: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_room_api_rooms__room_id__resume_post: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_room_api_rooms__room_id__start_post: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    room_game_api_rooms__room_id__game_get: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    room_action_api_rooms__room_id__actions_post: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
