/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Game */
        post: operations["create_game_api_games_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/archives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Archives */
        get: operations["list_archives_api_archives_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_api_games__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{session_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Game Action */
        post: operations["game_action_api_games__session_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Room */
        post: operations["create_room_api_rooms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Room */
        get: operations["get_room_api_rooms__room_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Room */
        post: operations["join_room_api_rooms__room_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/reconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconnect Room */
        post: operations["reconnect_room_api_rooms__room_id__reconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ready Room */
        post: operations["ready_room_api_rooms__room_id__ready_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Role Room */
        post: operations["role_room_api_rooms__room_id__role_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/seats/{seat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Local Seat */
        post: operations["update_local_seat_api_rooms__room_id__seats__seat_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Leave Room */
        post: operations["leave_room_api_rooms__room_id__leave_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Room */
        post: operations["pause_room_api_rooms__room_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Room */
        post: operations["resume_room_api_rooms__room_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Room */
        post: operations["start_room_api_rooms__room_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/events-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Room Events Ticket */
        get: operations["room_events_ticket_api_rooms__room_id__events_ticket_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Room Game */
        get: operations["room_game_api_rooms__room_id__game_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Room Action */
        post: operations["room_action_api_rooms__room_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionOption */
        ActionOption: {
            /** Id */
            id: string;
            type: components["schemas"]["ActionType"];
            /** Label */
            label: string;
            /**
             * Category Label
             * @default 基础行动
             */
            category_label: string;
            /**
             * Action Label
             * @default
             */
            action_label: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Cost */
            cost?: {
                [key: string]: number;
            };
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Disabled Reason */
            disabled_reason?: string | null;
            /** Targets */
            targets?: components["schemas"]["ActionTarget"][];
            /** Requirements */
            requirements?: string[];
            /**
             * Recommendation Score
             * @default 0
             */
            recommendation_score: number;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Preview Delta */
            preview_delta?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Confirmation
             * @default
             */
            confirmation: string;
            /** Payload */
            payload?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** ActionRequest */
        ActionRequest: {
            /** Player Id */
            player_id: string;
            action: components["schemas"]["ActionType"];
            /** Expected Revision */
            expected_revision: number;
            /** Target Id */
            target_id?: string | null;
            /** Target Site Id */
            target_site_id?: string | null;
            /** Card Id */
            card_id?: string | null;
            /** Recipient Id */
            recipient_id?: string | null;
            /** Route Id */
            route_id?: string | null;
            /** Upgrade Id */
            upgrade_id?: string | null;
            /** Target Ids */
            target_ids?: string[] | null;
            /** Request Id */
            request_id?: string | null;
        };
        /** ActionTarget */
        ActionTarget: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Preview Delta */
            preview_delta?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Payload */
            payload?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Recommendation Score
             * @default 0
             */
            recommendation_score: number;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /**
         * ActionType
         * @enum {string}
         */
        ActionType: "move" | "explore" | "interpret_evidence" | "form_interpretation" | "choose_intervention" | "restore" | "exchange" | "use_skill" | "play_card" | "end_turn" | "resolve_event" | "select_market_card" | "discard" | "survey_route" | "restore_route" | "establish_connection" | "prepare" | "select_upgrade" | "plan" | "use_action_card" | "use_node_ability" | "use_upgrade" | "end_planning";
        /** ArchivePlayer */
        ArchivePlayer: {
            /** Name */
            name: string;
            /** Role Id */
            role_id?: string | null;
        };
        /** ArchiveSummary */
        ArchiveSummary: {
            /** Archive Id */
            archive_id: string;
            /** Session Id */
            session_id: string;
            /** Room Id */
            room_id?: string | null;
            /** Mode */
            mode: string;
            /** Status */
            status: string;
            /** Scenario Id */
            scenario_id: string;
            /** Difficulty Id */
            difficulty_id: string;
            /** Turn */
            turn: number;
            /** Max Rounds */
            max_rounds: number;
            /** Updated At */
            updated_at?: string | null;
            outcome?: components["schemas"]["GameOutcome"] | null;
            /** Players */
            players?: components["schemas"]["ArchivePlayer"][];
        };
        /**
         * ChoiceKind
         * @enum {string}
         */
        ChoiceKind: "event" | "view_select" | "discard" | "action_card" | "archive_select" | "archive_retrieve" | "role_upgrade";
        /** CreateGameRequest */
        CreateGameRequest: {
            /** Player Ids */
            player_ids?: string[];
            /**
             * Difficulty Id
             * @default normal
             */
            difficulty_id: string;
            /**
             * Scenario Id
             * @default sand_and_stone
             */
            scenario_id: string;
            /** Seed */
            seed?: number | null;
            /** Daily Seed */
            daily_seed?: string | null;
        };
        /** EventForecastScope */
        EventForecastScope: {
            /** Target Rule */
            target_rule?: string | null;
            /**
             * Hidden Target Count
             * @default 0
             */
            hidden_target_count: number;
        };
        /** EventInstance */
        EventInstance: {
            /** Event Id */
            event_id?: string | null;
            /** @default forecast */
            status: components["schemas"]["EventStatus"];
            forecast_scope?: components["schemas"]["EventForecastScope"];
            /** Revealed Targets */
            revealed_targets?: string[];
            /** Resolved Targets */
            resolved_targets?: string[];
            /** Mitigation */
            mitigation?: components["schemas"]["EventRecord"][];
            /** Resolution */
            resolution?: components["schemas"]["EventRecord"][];
        };
        /** EventRecord */
        EventRecord: {
            /** Type */
            type?: string | null;
            /** Target Id */
            target_id?: string | null;
            /** Route Id */
            route_id?: string | null;
            /** Result */
            result?: string | null;
            /** Label */
            label?: string | null;
            /** Changes */
            changes?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Reason */
            reason?: string | null;
            /** Amount */
            amount?: number | null;
            /** Trigger */
            trigger?: string | null;
        };
        /**
         * EventStatus
         * @enum {string}
         */
        EventStatus: "forecast" | "resolved";
        /** FeedbackChange */
        FeedbackChange: {
            /** Metric */
            metric: string;
            /** Label */
            label: string;
            /** Before */
            before: number;
            /** After */
            after: number;
            /** Delta */
            delta: number;
        };
        /** FeedbackEvent */
        FeedbackEvent: {
            /**
             * Kind
             * @default state_change
             */
            kind: string;
            /** Message */
            message: string;
            /** Changes */
            changes?: components["schemas"]["FeedbackChange"][];
        };
        /**
         * GameOutcome
         * @enum {string}
         */
        GameOutcome: "victory" | "defeat";
        /** GameState */
        GameState: {
            /**
             * Schema Version
             * @default 3
             */
            schema_version: number;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Session Id */
            session_id: string;
            /**
             * Mode
             * @default heritage_network
             */
            mode: string;
            /**
             * Difficulty Id
             * @default normal
             */
            difficulty_id: string;
            /** Players */
            players: {
                [key: string]: components["schemas"]["PlayerState"];
            };
            /** Sites */
            sites: {
                [key: string]: components["schemas"]["SiteState"];
            };
            /** Tasks */
            tasks?: {
                [key: string]: {
                    [key: string]: components["schemas"]["JsonValue"];
                };
            };
            shared?: components["schemas"]["SharedState"];
            /** Decks */
            decks?: {
                [key: string]: string[];
            };
            /** Market */
            market?: string[];
            pending_choice?: components["schemas"]["PendingChoice"] | null;
            /** Action Options */
            action_options?: components["schemas"]["ActionOption"][];
            /**
             * Scenario Id
             * @default sand_and_stone
             */
            scenario_id: string;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Rng State
             * @default 0
             */
            rng_state: number;
            /**
             * Rng Position
             * @default 0
             */
            rng_position: number;
            /** Migrated From Schema Version */
            migrated_from_schema_version?: number | null;
            /** Routes */
            routes?: {
                [key: string]: components["schemas"]["RouteState"];
            };
            /** Projects */
            projects?: {
                [key: string]: components["schemas"]["ProjectState"];
            };
            /** Objectives */
            objectives?: {
                [key: string]: components["schemas"]["ObjectiveState"];
            };
            score?: components["schemas"]["ScoreState"];
            result?: components["schemas"]["ResultState"];
            viewer?: components["schemas"]["ViewerState"];
            /** Feedback Events */
            feedback_events?: components["schemas"]["FeedbackEvent"][];
            goal_status?: components["schemas"]["GoalStatus"];
            /** Processed Request Ids */
            processed_request_ids?: string[];
        };
        /** GoalCondition */
        GoalCondition: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Current */
            current: number;
            /** Target */
            target: number;
            /** Remaining */
            remaining: number;
            /**
             * Kind
             * @default progress
             * @enum {string}
             */
            kind: "progress" | "guardrail" | "deadline";
            /**
             * Operator
             * @default gte
             * @enum {string}
             */
            operator: "gte" | "lt" | "lte";
            /**
             * Status
             * @default incomplete
             * @enum {string}
             */
            status: "incomplete" | "safe" | "warning" | "completed" | "failed";
            /** Related Ids */
            related_ids?: string[];
            /** Related Labels */
            related_labels?: string[];
        };
        /** GoalStatus */
        GoalStatus: {
            /**
             * Core Projects Completed
             * @default 0
             */
            core_projects_completed: number;
            /**
             * Core Projects Target
             * @default 0
             */
            core_projects_target: number;
            /**
             * Objectives Completed
             * @default 0
             */
            objectives_completed: number;
            /**
             * Objectives Target
             * @default 0
             */
            objectives_target: number;
            /**
             * Protected Sites
             * @default 0
             */
            protected_sites: number;
            /**
             * Protected Sites Target
             * @default 0
             */
            protected_sites_target: number;
            /**
             * Weathering
             * @default 0
             */
            weathering: number;
            /**
             * Weathering Limit
             * @default 5
             */
            weathering_limit: number;
            /**
             * Rounds Remaining
             * @default 0
             */
            rounds_remaining: number;
            /** Victory Conditions */
            victory_conditions?: components["schemas"]["GoalCondition"][];
            /** Failure Conditions */
            failure_conditions?: components["schemas"]["GoalCondition"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        JsonValue: unknown;
        /** MetaResponse */
        MetaResponse: {
            /** Schema Version */
            schema_version: number;
            /** Mode */
            mode: string;
            /** Domains */
            domains: string[];
            /** Domain Meta */
            domain_meta?: {
                [key: string]: {
                    [key: string]: components["schemas"]["JsonValue"];
                };
            };
            /** Terminology */
            terminology?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Regions */
            regions?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Scenarios */
            scenarios?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Roles */
            roles?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Sites */
            sites?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Facets */
            facets?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Cards */
            cards?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Action Cards */
            action_cards?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Events */
            events?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Tasks */
            tasks?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Projects */
            projects?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Objectives */
            objectives?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Difficulty */
            difficulty?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Effective Rules Preview */
            effective_rules_preview?: {
                [key: string]: {
                    [key: string]: components["schemas"]["JsonValue"];
                };
            };
        };
        /** ObjectiveState */
        ObjectiveState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Target
             * @default 1
             */
            target: number;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Completed
             * @default false
             */
            completed: boolean;
        };
        /** PendingChoice */
        PendingChoice: {
            kind: components["schemas"]["ChoiceKind"];
            /** Options */
            options?: components["schemas"]["PendingChoiceOption"][];
            /** Cards */
            cards?: string[];
            /** Event Id */
            event_id?: string | null;
            /** Card Id */
            card_id?: string | null;
            /** Player Id */
            player_id?: string | null;
            /** Site Id */
            site_id?: string | null;
            /** Next Card Id */
            next_card_id?: string | null;
            /** Next Action Card Id */
            next_action_card_id?: string | null;
            /** Resume Choice */
            resume_choice?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
        };
        /** PendingChoiceOption */
        PendingChoiceOption: {
            /** Id */
            id: string;
            /** Label */
            label?: string | null;
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Trigger */
            trigger?: string | null;
            /** Strategic Direction */
            strategic_direction?: string | null;
        };
        /**
         * Phase
         * @enum {string}
         */
        Phase: "round_forecast" | "planning" | "player_action" | "pending_choice" | "event_resolution" | "round_summary" | "game_over";
        /**
         * PlayMode
         * @enum {string}
         */
        PlayMode: "solo" | "local" | "multi_device";
        /** PlayerState */
        PlayerState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Role Id */
            role_id: string;
            /** Location */
            location: string;
            /**
             * Ap
             * @default 3
             */
            ap: number;
            /**
             * Max Ap
             * @default 3
             */
            max_ap: number;
            /**
             * Influence
             * @default 0
             */
            influence: number;
            /**
             * Durability
             * @default 3
             */
            durability: number;
            /** Hand */
            hand?: string[];
            /** Action Hand */
            action_hand?: string[];
            /**
             * Supplies
             * @default 0
             */
            supplies: number;
            /** Flags */
            flags?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Skill Used
             * @default false
             */
            skill_used: boolean;
            /**
             * Contributions
             * @default 0
             */
            contributions: number;
            /** Upgrades */
            upgrades?: string[];
        };
        /** ProjectState */
        ProjectState: {
            /** Id */
            id: string;
            /** Site Id */
            site_id: string;
            /** Name */
            name: string;
            /** Stages */
            stages?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /**
             * Stage Index
             * @default 0
             */
            stage_index: number;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** @default active */
            status: components["schemas"]["ProjectStatus"];
            /** Contributors */
            contributors?: string[];
            /** Stage Evidence */
            stage_evidence?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Completed Stages */
            completed_stages?: string[];
            /** Stage Progress */
            stage_progress?: {
                [key: string]: number;
            };
            /** Stage Contributors */
            stage_contributors?: {
                [key: string]: string[];
            };
            /** Stage Receipts */
            stage_receipts?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Available Choices */
            available_choices?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "active" | "completed";
        /** ResultState */
        ResultState: {
            outcome?: components["schemas"]["GameOutcome"] | null;
            /** Outcome Reason */
            outcome_reason?: string | null;
            /**
             * Outcome Summary
             * @default
             */
            outcome_summary: string;
            score?: components["schemas"]["ScoreState"];
            /** Completed Objectives */
            completed_objectives?: string[];
            /** Completed Projects */
            completed_projects?: string[];
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
        /** RoomActionRequest */
        RoomActionRequest: {
            action: components["schemas"]["ActionType"];
            /** Expected Revision */
            expected_revision: number;
            /** Target Id */
            target_id?: string | null;
            /** Target Site Id */
            target_site_id?: string | null;
            /** Card Id */
            card_id?: string | null;
            /** Recipient Id */
            recipient_id?: string | null;
            /** Route Id */
            route_id?: string | null;
            /** Upgrade Id */
            upgrade_id?: string | null;
            /** Target Ids */
            target_ids?: string[] | null;
            /** Request Id */
            request_id?: string | null;
        };
        /** RoomCreateRequest */
        RoomCreateRequest: {
            /**
             * Play Mode
             * @default solo
             */
            play_mode: string;
            /**
             * Name
             * @default 同行者
             */
            name: string;
            /** Role Id */
            role_id?: string | null;
            /**
             * Scenario Id
             * @default sand_and_stone
             */
            scenario_id: string;
            /**
             * Difficulty Id
             * @default guided
             */
            difficulty_id: string;
            /** Seed */
            seed?: number | null;
            /**
             * Max Players
             * @default 4
             */
            max_players: number;
        };
        /** RoomCredentials */
        RoomCredentials: {
            room: components["schemas"]["RoomPublic"];
            /** Host Token */
            host_token?: string | null;
            /** Seat Token */
            seat_token: string;
            /** Session Id */
            session_id?: string | null;
        };
        /** RoomEventTicket */
        RoomEventTicket: {
            /** Ticket */
            ticket: string;
            /** Expires In */
            expires_in: number;
        };
        /** RoomJoinRequest */
        RoomJoinRequest: {
            /**
             * Name
             * @default 同行者
             */
            name: string;
            /** Role Id */
            role_id?: string | null;
        };
        /** RoomPublic */
        RoomPublic: {
            /** Room Id */
            room_id: string;
            /** Status */
            status: string;
            /** Play Mode */
            play_mode: string;
            /** Scenario Id */
            scenario_id: string;
            /** Difficulty Id */
            difficulty_id: string;
            /** Max Players */
            max_players: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Viewer Seat Id */
            viewer_seat_id?: string | null;
            /** Seats */
            seats?: components["schemas"]["RoomSeat"][];
        };
        /** RoomReadyRequest */
        RoomReadyRequest: {
            /**
             * Ready
             * @default true
             */
            ready: boolean;
        };
        /** RoomReconnectRequest */
        RoomReconnectRequest: {
            /** Seat Id */
            seat_id: string;
        };
        /** RoomRoleRequest */
        RoomRoleRequest: {
            /** Role Id */
            role_id: string;
        };
        /** RoomSeat */
        RoomSeat: {
            /** Seat Id */
            seat_id: string;
            /** Name */
            name: string;
            /** Role Id */
            role_id?: string | null;
            /**
             * Ready
             * @default false
             */
            ready: boolean;
            /**
             * Connected
             * @default false
             */
            connected: boolean;
            /**
             * Role Locked
             * @default false
             */
            role_locked: boolean;
        };
        /** RoomSeatUpdateRequest */
        RoomSeatUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Role Id */
            role_id?: string | null;
            /** Ready */
            ready?: boolean | null;
        };
        /** RoomStartResponse */
        RoomStartResponse: {
            room: components["schemas"]["RoomPublic"];
            /** Session Id */
            session_id: string;
        };
        /** RoundMetrics */
        RoundMetrics: {
            /**
             * Weathering
             * @default 0
             */
            weathering: number;
            /**
             * Weathering Track
             * @default 0
             */
            weathering_track: number;
            /**
             * Restoration Resource
             * @default 0
             */
            restoration_resource: number;
            /**
             * Research Clues
             * @default 0
             */
            research_clues: number;
            /**
             * Influence
             * @default 0
             */
            influence: number;
        };
        /** RoundSummary */
        RoundSummary: {
            /**
             * Round
             * @default 0
             */
            round: number;
            /** Event Id */
            event_id?: string | null;
            /** Event Targets */
            event_targets?: string[];
            /** Event Resolution */
            event_resolution?: components["schemas"]["EventRecord"][];
            before?: components["schemas"]["RoundMetrics"];
            after?: components["schemas"]["RoundMetrics"];
            /**
             * Planning Mark Count
             * @default 0
             */
            planning_mark_count: number;
            /**
             * Completed Projects
             * @default 0
             */
            completed_projects: number;
            /**
             * Completed Objectives
             * @default 0
             */
            completed_objectives: number;
            /** Player Contributions */
            player_contributions?: {
                [key: string]: number;
            };
            /** Round Effects */
            round_effects?: components["schemas"]["EventRecord"][];
        };
        /** RouteState */
        RouteState: {
            /** Id */
            id: string;
            /** From Site */
            from_site: string;
            /** To Site */
            to_site: string;
            /**
             * Cost
             * @default 1
             */
            cost: number;
            /** @default open */
            status: components["schemas"]["RouteStatus"];
            /**
             * Risk
             * @default 0
             */
            risk: number;
            /**
             * Connection Level
             * @default 0
             */
            connection_level: number;
            /** Active Project Id */
            active_project_id?: string | null;
            /** Tags */
            tags?: string[];
            /** Waypoints */
            waypoints?: number[][];
            /**
             * Road Class
             * @default local
             */
            road_class: string;
            /**
             * Terrain
             * @default plain
             */
            terrain: string;
            /** Label Position */
            label_position?: number[] | null;
            /** Name */
            name?: string | null;
            /** Strategic Role */
            strategic_role?: string | null;
            /** Risk Profile */
            risk_profile?: string | null;
            /** Ui Hint */
            ui_hint?: string | null;
            /** Event Tags */
            event_tags?: string[];
        };
        /**
         * RouteStatus
         * @enum {string}
         */
        RouteStatus: "open" | "strained" | "blocked" | "restored" | "illuminated";
        /** ScoreState */
        ScoreState: {
            /**
             * Tasks
             * @default 0
             */
            tasks: number;
            /**
             * Routes
             * @default 0
             */
            routes: number;
            /**
             * Diversity
             * @default 0
             */
            diversity: number;
            /**
             * Protection
             * @default 0
             */
            protection: number;
            /**
             * Resources
             * @default 0
             */
            resources: number;
            /**
             * Efficiency
             * @default 0
             */
            efficiency: number;
            /**
             * Discovery
             * @default 0
             */
            discovery: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Grade
             * @default stone
             */
            grade: string;
        };
        /** SharedState */
        SharedState: {
            /**
             * Turn
             * @default 1
             */
            turn: number;
            /**
             * Max Rounds
             * @default 8
             */
            max_rounds: number;
            /**
             * Active Player Id
             * @default p1
             */
            active_player_id: string;
            /** Player Order */
            player_order?: string[];
            /**
             * Threat
             * @default 0
             */
            threat: number;
            /**
             * Influence
             * @default 0
             */
            influence: number;
            /**
             * Restoration Resource
             * @default 6
             */
            restoration_resource: number;
            /** Completed Domains */
            completed_domains?: string[];
            /** Current Event Id */
            current_event_id?: string | null;
            outcome?: components["schemas"]["GameOutcome"] | null;
            /** Outcome Reason */
            outcome_reason?: string | null;
            /**
             * Scenario Id
             * @default sand_and_stone
             */
            scenario_id: string;
            /**
             * Research Clues
             * @default 0
             */
            research_clues: number;
            /** Prepared Event Ids */
            prepared_event_ids?: string[];
            /**
             * Route Connection Score
             * @default 0
             */
            route_connection_score: number;
            /** Log */
            log?: string[];
            /** Planning Marks */
            planning_marks?: {
                [key: string]: {
                    [key: string]: string;
                }[];
            };
            /** Node Ability Uses */
            node_ability_uses?: string[];
            /** @default player_action */
            phase: components["schemas"]["Phase"];
            /**
             * Weathering Track
             * @default 0
             */
            weathering_track: number;
            /**
             * Weathering Limit
             * @default 5
             */
            weathering_limit: number;
            /** Effective Rules */
            effective_rules?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Solo Mode
             * @default false
             */
            solo_mode: boolean;
            /** Controlled Character Ids */
            controlled_character_ids?: string[];
            /** Journal */
            journal?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Event Targets */
            event_targets?: string[];
            event_instance?: components["schemas"]["EventInstance"];
            /** Event History */
            event_history?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            round_summary?: components["schemas"]["RoundSummary"];
            /** Reserved Market Cards */
            reserved_market_cards?: string[];
            /** Scenario Rule Uses */
            scenario_rule_uses?: string[];
            /** Scenario Round Baseline */
            scenario_round_baseline?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** SiteState */
        SiteState: {
            /** Id */
            id: string;
            /**
             * Damage
             * @default 0
             */
            damage: number;
            /**
             * Max Damage
             * @default 3
             */
            max_damage: number;
            /**
             * Durability
             * @default 3
             */
            durability: number;
            /**
             * Max Durability
             * @default 3
             */
            max_durability: number;
            /** @default stable */
            status: components["schemas"]["SiteStatus"];
            /**
             * Influence
             * @default 0
             */
            influence: number;
            /**
             * Discovered
             * @default false
             */
            discovered: boolean;
            /** Domains */
            domains?: string[];
            /** Contributions */
            contributions?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Active Project Id */
            active_project_id?: string | null;
        };
        /**
         * SiteStatus
         * @enum {string}
         */
        SiteStatus: "stable" | "at_risk" | "closed";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ViewerSeat */
        ViewerSeat: {
            /** Seat Id */
            seat_id: string;
            /** Player Id */
            player_id?: string | null;
            /** Name */
            name?: string | null;
            /** Role Id */
            role_id?: string | null;
            /**
             * Ready
             * @default false
             */
            ready: boolean;
            /**
             * Connected
             * @default false
             */
            connected: boolean;
        };
        /** ViewerState */
        ViewerState: {
            /** Seat Id */
            seat_id?: string | null;
            /** Player Id */
            player_id?: string | null;
            /** Controlled Player Ids */
            controlled_player_ids?: string[];
            /**
             * Can Act
             * @default false
             */
            can_act: boolean;
            /**
             * Can Manage Room
             * @default false
             */
            can_manage_room: boolean;
            /** @default solo */
            play_mode: components["schemas"]["PlayMode"];
            /**
             * Paused
             * @default false
             */
            paused: boolean;
            /** Room Id */
            room_id?: string | null;
            /** Room Status */
            room_status?: string | null;
            /** Seats */
            seats?: components["schemas"]["ViewerSeat"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    create_game_api_games_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_archives_api_archives_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveSummary"][];
                };
            };
        };
    };
    get_game_api_games__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    game_action_api_games__session_id__actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_room_api_rooms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomCredentials"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_room_api_rooms__room_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_room_api_rooms__room_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomJoinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomCredentials"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconnect_room_api_rooms__room_id__reconnect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomReconnectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomCredentials"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_room_api_rooms__room_id__ready_post: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomReadyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    role_room_api_rooms__room_id__role_post: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_local_seat_api_rooms__room_id__seats__seat_id__post: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
                seat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomSeatUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leave_room_api_rooms__room_id__leave_post: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_room_api_rooms__room_id__pause_post: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_room_api_rooms__room_id__resume_post: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_room_api_rooms__room_id__start_post: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    room_events_ticket_api_rooms__room_id__events_ticket_get: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomEventTicket"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    room_game_api_rooms__room_id__game_get: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    room_action_api_rooms__room_id__actions_post: {
        parameters: {
            query?: never;
            header?: {
                "x-seat-token"?: string | null;
            };
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
