import type { components } from '../shared/api/generated';
export type ActionType = components['schemas']['ActionType'];
export type SiteStatus = components['schemas']['SiteStatus'];
export type Phase = components['schemas']['Phase'];
export type RouteStatus = components['schemas']['RouteStatus'];
export type ProjectStatus = components['schemas']['ProjectStatus'];
export type ChoiceKind = components['schemas']['ChoiceKind'];
export type EventStatus = components['schemas']['EventStatus'];
export type PlayMode = components['schemas']['PlayMode'];
export type GameOutcome = components['schemas']['GameOutcome'] | null;
export interface Action { type: ActionType; label: string; description?: string; cost?: number; target_id?: string; target_site_id?: string; target_ids?: string[]; card_id?: string; recipient_id?: string; route_id?: string; upgrade_id?: string; skill?: string; request_id?: string; preview_delta?: Record<string, unknown>; requirements?: string[]; }
export interface ActionTarget { id: string; label: string; preview_delta?: Record<string, unknown>; payload?: Partial<Action> & Record<string, unknown>; recommendation_score?: number; reason?: string; }
export interface ActionOption { id: string; type: ActionType; label: string; category_label?: string; action_label?: string; description?: string; cost?: Record<string, number>; enabled?: boolean; disabled_reason?: string; targets: ActionTarget[]; requirements?: string[]; recommendation_score?: number; reason?: string; preview_delta?: Record<string, unknown>; confirmation?: string; payload?: Partial<Action> & Record<string, unknown>; }
export interface Player { id: string; name: string; role_id: string; location: string; ap: number; max_ap: number; influence: number; durability: number; hand: string[]; action_hand?: string[]; supplies?: number; skill_used: boolean; contributions: number; upgrades?: string[]; }
export interface Site { id: string; name?: string; summary?: string; icon_asset?: string; scene_asset?: string; x?: number; y?: number; layout?: { x?: number; y?: number; labelAnchor?: 'left' | 'right' | 'above' | 'below' }; node_kind?: 'core' | 'support' | 'event'; kind?: string; content_class?: 'documented' | 'interpretive' | 'gameplay'; damage: number; max_damage: number; durability: number; max_durability: number; status: SiteStatus | 'event'; influence: number; discovered: boolean; domains: string[]; contributions: Array<{ player_id: string; card_id: string; origin_tags?: string[] }>; active_task_id?: string; connections?: string[]; node_ability?: { name: string; description: string }; }
export interface TaskRequirement { key: string; label: string; current?: number; target?: number; complete: boolean; missing?: string[]; }
export interface Task { id?: string; name: string; culture_explanation?: string; ui_instruction?: string; required_domains: string[]; required_origin_diversity: number; required_card_count: number; required_cards_per_player_min?: number; combo_requirement?: { required_combo_tags?: string[]; preferred_origins?: string[]; minimum_distinct_players?: number }; reward?: Record<string, number | string>; contributed_cards: string[]; completed: boolean; interpretation?: { placements: Array<{ card_id: string; relation: 'support' | 'conflict' | 'pending'; player_id: string }>; formed: boolean; intervention: 'act_now' | 'minimal' | 'record' | null; confidence: number }; progress?: { requirements: TaskRequirement[]; complete: boolean; interpretation?: { reason?: string; missing_domains?: string[]; missing_origins?: string[]; missing_tags?: string[]; can_form?: boolean } }; }
export interface Shared { turn: number; max_rounds: number; active_player_id: string; player_order: string[]; influence: number; restoration_resource: number; completed_domains: string[]; current_event_id: string | null; outcome: GameOutcome; outcome_reason?: string | null; scenario_id?: string; research_clues?: number; prepared_event_ids?: string[]; route_connection_score?: number; phase?: Phase; weathering_track?: number; weathering_limit?: number; effective_rules?: Record<string, number>; solo_mode?: boolean; controlled_character_ids?: string[]; journal?: Array<{ id: string; round: number; type: string; message: string; effects: unknown[]; created_at: string; player_id?: string }>; event_targets?: string[]; event_instance?: { event_id?: string; forecast_scope?: { target_rule?: string; hidden_target_count?: number }; revealed_targets?: string[]; resolved_targets?: string[]; mitigation?: Array<Record<string, unknown>>; resolution?: Array<{ target_id?: string | null; label?: string; changes?: Record<string, string | number>; reason?: string }>; status?: EventStatus }; event_history?: Array<{ event_id?: string; round?: number; resolution?: Array<{ changes?: Record<string, string | number> }> }>; planning_marks?: Record<string, Array<{ target_id: string; turn: string; collaborated?: boolean; collaboration_action?: string }>>; round_summary?: components['schemas']['RoundSummary']; log: string[]; }
export interface RouteState { id: string; from_site: string; to_site: string; cost: number; status: RouteStatus; risk: number; connection_level: number; active_project_id?: string | null; tags?: string[]; waypoints?: Array<[number, number]>; road_class?: string; terrain?: string; label_position?: [number, number] | null; name?: string; strategic_role?: string; risk_profile?: string; ui_hint?: string; event_tags?: string[]; }
export interface ProjectState { id: string; site_id: string; name: string; stages: Array<{ id: string; name?: string; required_progress?: number; action_type?: string; stage_text?: string; requirements?: Record<string, unknown>; reward?: Record<string, number | string | boolean | string[]> }>; stage_index: number; progress: number; status: ProjectStatus; contributors: string[]; stage_evidence?: Array<Record<string, unknown>>; completed_stages?: string[]; stage_progress?: Record<string, number>; stage_contributors?: Record<string, string[]>; available_choices?: Array<Record<string, unknown>>; }
export interface ObjectiveState { id: string; name: string; type: string; target: number; progress: number; completed: boolean; }
export interface ScoreState { tasks: number; routes: number; diversity: number; protection: number; resources: number; efficiency: number; discovery: number; total: number; grade?: string; }
export type GoalCondition = components['schemas']['GoalCondition'];
export type GoalStatus = components['schemas']['GoalStatus'];
export type FeedbackChange = components['schemas']['FeedbackChange'];
export type FeedbackEvent = components['schemas']['FeedbackEvent'];
export type ResultState = components['schemas']['ResultState'];
export type ViewerState = components['schemas']['ViewerState'];
export interface GameState { schema_version: number; revision: number; session_id: string; mode: string; difficulty_id: string; scenario_id?: string; seed?: number; rng_state?: number; rng_position?: number; players: Record<string, Player>; sites: Record<string, Site>; tasks: Record<string, Task>; shared: Shared; decks: Record<string, string[]>; market: string[]; pending_choice: { kind: ChoiceKind; event_id?: string; options?: Array<{ id: string; label: string }>; cards?: string[] } | null; action_options?: ActionOption[]; feedback_events?: FeedbackEvent[]; goal_status?: GoalStatus; routes?: Record<string, RouteState>; projects?: Record<string, ProjectState>; objectives?: Record<string, ObjectiveState>; score?: ScoreState; result?: ResultState; viewer?: ViewerState; }
export interface ContentCard { id: string; name: string; icon_asset?: string; domain?: string; origin_tags?: string[]; description?: string; summary?: string; combo_name?: string; combo_tags?: string[]; combo_reward_text?: string; evidence_use_text?: string; instant_use_text?: string; strategic_role?: string; effect?: Record<string, unknown>; }
export interface ContentEvent { id: string; name: string; scene_asset?: string; description?: string; summary?: string; forecast_text?: string; mitigation_hint?: string; mitigation?: Array<Record<string, unknown>>; preview_delta?: Record<string, unknown>; target_rule?: string; action_cost_modifiers?: Record<string, number>; severity?: number; tags?: string[]; effect?: Record<string, unknown>; }
export interface ContentRole { id: string; name: string; origin?: string; icon?: string; icon_asset?: string; color?: string; meaning?: string; team_role?: string; play_style?: string; solo_rule?: string; starting_hint?: string; upgrade_ids?: string[]; start_site_id?: string; summary?: string; ability?: { name: string; action: string; description?: string; ap_cost?: number; max_hops?: number }; }
export interface DomainMeta { name: string; short_name: string; color_token?: string; }
export interface Region { id: string; name: string; site_ids: string[]; label_position?: { x: number; y: number }; hull_points?: Array<{ x: number; y: number }>; visual_token?: string; description?: string; content_review_status?: string; }
export interface Scenario { id: string; name: string; description?: string; recommended_minutes?: string | number; max_rounds?: number; recommended_players?: number[]; victory_brief?: string; failure_brief?: string; scenario_rule?: { description?: string; trigger?: string; effect?: { type?: string; amount?: number }; additional_effects?: Array<{ trigger?: string; effect?: { type?: string; amount?: number } }> }; }
export interface Meta { schema_version: number; mode: string; domains: string[]; domain_meta: Record<string, DomainMeta>; terminology?: Record<string, unknown>; regions?: Region[]; scenarios?: Scenario[]; roles: ContentRole[]; sites: Site[]; cards: ContentCard[]; action_cards?: Array<Record<string, unknown>>; events: ContentEvent[]; tasks: Task[]; projects?: ProjectState[]; objectives?: ObjectiveState[]; facets?: Array<Record<string, unknown>>; difficulty: Array<{ id: string; name?: string; description?: string; max_rounds?: number; restoration_resource?: number; event_weight?: number; node_damage_base?: number; event_preview_count?: number; recommended_experience?: string; solo_ap_bonus?: number }>; effective_rules_preview?: Record<string, Record<string, number | string>>; }
export interface RoomSeat { seat_id: string; name: string; role_id?: string | null; ready: boolean; connected: boolean; role_locked?: boolean; }
export interface Room { room_id: string; status: string; play_mode: PlayMode; scenario_id: string; difficulty_id: string; max_players: number; session_id?: string | null; viewer_seat_id?: string | null; seats: RoomSeat[]; created_at?: string; updated_at?: string; }
export type RoomCredentials = components['schemas']['RoomCredentials'];
export interface ArchiveSummary { archive_id: string; session_id: string; room_id?: string | null; mode: PlayMode | string; status: string; scenario_id: string; difficulty_id: string; turn: number; max_rounds: number; updated_at?: string | null; outcome?: GameOutcome; players: Array<{ name: string; role_id?: string | null }>; }
