import { type FormEvent, useState } from 'react';
import { ArrowRight, BookOpen, Compass, Dice5, Users } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { api } from '../../shared/api/client';
import type { Meta } from '../../types/game';

export function LandingPage() {
  const navigate = useNavigate(); const [count, setCount] = useState(2); const [difficulty, setDifficulty] = useState('normal'); const [scenario, setScenario] = useState('sand_and_stone'); const [seedText, setSeedText] = useState(''); const [showSeed, setShowSeed] = useState(false); const [session, setSession] = useState(''); const [busy, setBusy] = useState(false);
  const { data: meta, isError } = useQuery<Meta>({ queryKey: ['meta'], queryFn: api.meta });
  async function create(event: FormEvent) { event.preventDefault(); setBusy(true); try { const game = await api.create(Array.from({ length: count }, (_, index) => `p${index + 1}`), difficulty, { scenario_id: scenario, ...(seedText.trim() ? { seed: Number(seedText) || 1 } : {}) }); navigate(`/game/${game.session_id}`); } finally { setBusy(false); } }
  const scenarios = meta?.scenarios || [{ id: 'sand_and_stone', name: '风沙与石' }];
  return <main className="landing"><div className="landing-copy"><div className="eyebrow">云冈 · 数字遗产协作体验</div><h1>石窟<br /><em>光谱</em></h1><p>一张会随着探索、修护与协作逐步显影的文化关系图。你们要让散落在时间中的证据重新彼此照见。</p><div className="landing-facts"><span><Compass />15-25 分钟</span><span><Users />2-4 人协作</span><span><BookOpen />共同修复遗产网络</span></div></div><section className="start-panel" aria-labelledby="start-title"><div className="panel-kicker">创建一场共同旅程</div><h2 id="start-title">从一束光开始</h2><p>{isError ? '暂时无法读取场景，仍可用默认场景开始。' : '选择队伍与场景；完成一轮探索、贡献和修护。'}</p><form onSubmit={create}><label>同行人数<div className="segmented">{[2, 3, 4].map(value => <button type="button" key={value} className={count === value ? 'selected' : ''} onClick={() => setCount(value)} aria-pressed={count === value}>{value} 人</button>)}</div></label><label>旅程场景<div className="segmented">{scenarios.slice(0, 3).map(item => <button type="button" key={item.id} className={scenario === item.id ? 'selected' : ''} onClick={() => setScenario(item.id)} aria-pressed={scenario === item.id}>{item.name}</button>)}</div></label><label>旅程难度<select value={difficulty} onChange={event => setDifficulty(event.target.value)}>{(meta?.difficulty || [{ id: 'normal', name: '标准旅程' }]).map(item => <option key={item.id} value={item.id}>{item.name || item.id}</option>)}</select></label><button type="button" className="ghost-button" onClick={() => setShowSeed(value => !value)} aria-expanded={showSeed}><Dice5 size={15} />{showSeed ? '收起可复现设置' : '可复现设置'}</button>{showSeed && <label htmlFor="seed">旅程种子<input id="seed" inputMode="numeric" value={seedText} onChange={event => setSeedText(event.target.value)} placeholder="例如 20260726" /></label>}<button className="primary-cta" disabled={busy}>{busy ? '正在点亮路线…' : '创建旅程'}<ArrowRight /></button></form><div className="resume"><label htmlFor="session">恢复已有旅程</label><div><input id="session" value={session} onChange={event => setSession(event.target.value)} placeholder="输入旅程编号" /><button type="button" disabled={!session.trim()} onClick={() => navigate(`/game/${session.trim()}`)}>进入</button></div></div></section></main>;
}
