import { Archive, ChevronDown, Compass, HandHeart, Hammer, MapPinned, ScanSearch, ShieldPlus, Sparkles, WandSparkles } from 'lucide-react';
import type { Action, ActionType, ContentCard, GameState, Player } from '../../types/game';

function findCardAction(actions: Action[], type: ActionType, cardId: string) { return actions.find(action => action.type === type && action.card_id === cardId); }
const actionIcons: Partial<Record<ActionType, typeof Sparkles>> = { move: MapPinned, survey_route: ScanSearch, explore: Compass, contribute: HandHeart, restore: Hammer, restore_route: ShieldPlus, establish_connection: WandSparkles, prepare: ShieldPlus, use_skill: Sparkles, end_turn: Archive };
const actionNotes: Partial<Record<ActionType, string>> = { move: '沿已显影的路线前往新地点', explore: '从当前地点发现文化证据', contribute: '将手中的证据投入节点任务', restore: '修复受损的节点或线路', survey_route: '勘察一条尚未明确的线路', restore_route: '让受阻路线重新可通行', establish_connection: '为两个地点建立稳定联系', prepare: '保留力量，等待下一次决定', use_skill: '使用角色的专长改变局势', end_turn: '结束本回合并结算事件' };
const primaryOrder: ActionType[] = ['move', 'explore', 'contribute', 'restore', 'survey_route'];

export function CommandDock({ state: _state, active, cards, legal, actionsByType, actionMode, actionLabels, mutationPending, onRun, onChoose, onCancel, onCard, onContribution }: { state: GameState; active: Player; cards: Record<string, ContentCard>; legal: Action[]; actionsByType: Map<ActionType, Action[]>; actionMode: ActionType | null; actionLabels: Partial<Record<ActionType, string>>; mutationPending: boolean; onRun: (action?: Action) => void; onChoose: (type: ActionType) => void; onCancel: () => void; onCard: (id: string) => void; onContribution: (id: string) => void }) {
  const available = Array.from(actionsByType.entries()).filter(([, actions]) => actions.length).map(([type, actions]) => ({ type, action: actions[0] }));
  const featured = primaryOrder.map(type => available.find(item => item.type === type)).filter((item): item is { type: ActionType; action: Action } => Boolean(item)).slice(0, 3);
  const more = available.filter(item => !featured.some(feature => feature.type === item.type));
  const select = (type: ActionType, action: Action) => { if (type === 'prepare' || type === 'use_action_card' || type === 'use_skill' || type === 'end_turn') onRun(action); else onChoose(type); };
  return <section className="lower-dock command-deck" aria-label="行动抉择台">
    <div className="dock-summary"><span className="section-label"><Hammer size={14} />行动抉择</span><div className="ap-readout"><b>{active.ap}</b><span>AP<br />可用行动点</span></div><span className="dock-hint">{actionMode ? `正在选择「${actionLabels[actionMode]}」的合法目标` : featured.length ? '选择一种行动，地图会告诉你可以在哪里落子。' : '当前没有可执行行动。'}</span>{actionMode && <button className="ghost-button" onClick={onCancel}>返回浏览</button>}</div>
    <div className="featured-actions">{featured.map(({ type, action }, index) => { const Icon = actionIcons[type] || Sparkles; const selected = actionMode === type; return <button key={type} className={`action-card action-${type} ${selected ? 'selected' : ''} ${index === 0 ? 'lead-action' : ''}`} disabled={mutationPending} onClick={() => select(type, action)}><span className="action-card-icon"><Icon size={20} /></span><span className="action-card-copy"><b>{actionLabels[type] || type}</b><small>{selected ? '在地图或证据中选择目标' : actionNotes[type]}</small></span><span className="action-cost">{action.cost || 0}<small>AP</small></span></button>; })}{!featured.length && <div className="hand-empty">行动正在等待下一次事件结算。</div>}<details className="more-actions"><summary aria-label={`展开更多行动，共 ${more.length} 项`}>更多行动 <span>{more.length}</span><ChevronDown size={14} /></summary><div>{more.map(({ type, action }) => { const Icon = actionIcons[type] || Sparkles; return <button key={type} disabled={mutationPending} onClick={() => select(type, action)}><Icon size={15} /><b>{actionLabels[type] || type}</b>{action.cost ? <small>{action.cost} AP</small> : null}</button>; })}</div></details></div>
    <div className="hand-tray"><div className="section-label"><Archive size={14} />我的手牌 <b>{active.hand.length} / 3</b></div><div className="hand-cards">{active.hand.length ? active.hand.map(id => { const item = cards[id]; const contributeAction = findCardAction(legal, 'contribute', id); const playAction = findCardAction(legal, 'play_card', id); return <button key={id} className={`hand-card ${actionMode === 'contribute' && contributeAction ? 'selected' : ''}`} onClick={() => { if (actionMode === 'contribute' && contributeAction) onRun(contributeAction); else if (contributeAction) onContribution(id); else onCard(id); }}><img src={`/ui-assets/${item?.icon_asset || 'icon_card_scroll.png'}`} alt="" /><b>{item?.name || id}</b><small>{actionMode === 'contribute' && contributeAction ? '点击投入任务' : playAction ? '查看或使用' : '查看证据'}</small></button>; }) : <div className="hand-empty">探索后获得的文化证据会在这里等待组合。</div>}</div></div>
  </section>;
}
