import type { GameState } from '../../types/game';

function Progress({ value, max }: { value: number; max: number }) { return <div className="progress gold"><span style={{ width: `${Math.min(100, max ? value / max * 100 : 0)}%` }} /></div>; }

export function ScenarioHeader({ state, connection }: { state: GameState; connection: string }) {
  const projects = Object.values(state.projects || {}); const completedProjects = projects.filter(project => project.status === 'completed').length; const objectives = Object.values(state.objectives || {}); const completedObjectives = objectives.filter(objective => objective.completed).length; const influenceGoal = Math.max(1, ...objectives.filter(objective => objective.type === 'influence').map(objective => objective.target), state.shared.effective_rules?.influence_goal || 1);
  const phase = state.shared.phase === 'planning' ? '规划阶段' : state.shared.phase === 'pending_choice' ? '等待回应' : '行动阶段';
  return <header className="game-header"><a className="brand-mark" href="/" aria-label="返回首页"><img src="/ui-assets/04_yungang_seal_stamp.webp" alt="" /><span>石窟<strong>光谱</strong></span></a><div className="header-center"><div className="goal-hud" aria-label="共同目标进度"><div className="goal-hud-head"><span className="goal-title">共同目标</span><span className="goal-phase">第 {state.shared.turn} / {state.shared.max_rounds} 回合 · {phase}</span></div><div className="goal-line"><Progress value={state.shared.influence} max={influenceGoal} /><b>{state.shared.influence} / {influenceGoal} 共同影响</b></div><div className="goal-context"><span>项目 {completedProjects} / {projects.length || 0}</span><span>目标 {completedObjectives} / {objectives.length || 0}</span><span>压力 {state.shared.weathering_track ?? state.shared.threat}</span></div></div></div><div className="header-actions">{connection !== '已连接' && <span className={`sync-state ${connection === '离线' ? 'offline' : ''}`} aria-live="polite"><span />{connection}</span>}</div></header>;
}
