import type { GameState } from '../../types/game';

function Progress({ value, max }: { value: number; max: number }) { return <div className="progress gold"><span style={{ width: `${Math.min(100, max ? value / max * 100 : 0)}%` }} /></div>; }

export function ScenarioHeader({ state, scenarioName, connection }: { state: GameState; scenarioName: string; connection: string }) {
  const projects = Object.values(state.projects || {}); const objectives = Object.values(state.objectives || {}); const goal = state.goal_status;
  const completedProjects = goal?.core_projects_completed ?? projects.filter(project => project.status === 'completed').length; const completedObjectives = goal?.objectives_completed ?? objectives.filter(objective => objective.completed).length;
  const phase = state.shared.phase === 'planning' ? '规划阶段' : state.shared.phase === 'pending_choice' ? '等待回应' : '行动阶段';
  const victory = goal?.victory_conditions || [];
  const failure = goal?.failure_conditions || [];
  return <header className="game-header"><a className="brand-mark" href="/" aria-label="返回首页"><img src="/ui-assets/04_yungang_seal_stamp.webp" alt="" /><span>石窟<strong>光谱</strong></span></a><div className="header-center"><div className="scenario-name" aria-label="当前游玩主题">主题 · {scenarioName}</div><div className="goal-hud" aria-label="共同目标进度"><div className="goal-hud-head"><span className="goal-title">胜利清单</span><span className="goal-phase">第 {state.shared.turn} / {state.shared.max_rounds} 回合 · {phase}</span></div><div className="goal-conditions"><div><b>要完成</b>{victory.map(item => <span key={item.id} className={item.current >= item.target ? 'condition-done' : ''}><i>{item.current >= item.target ? '✓' : '·'}</i>{item.label} {item.current} / {item.target}{item.remaining > 0 && <small>还差 {item.remaining}</small>}</span>)}</div><div><b>不能超过</b>{failure.map(item => <span key={item.id} className={item.current >= item.target ? 'condition-danger' : ''}><i>{item.current >= item.target ? '!' : '·'}</i>{item.label} {item.current} / {item.target}{item.remaining > 0 && <small>余量 {item.remaining}</small>}</span>)}</div></div><div className="goal-context"><span>核心项目 {completedProjects} / {goal?.core_projects_target || 0}</span><span>公共目标 {completedObjectives} / {goal?.objectives_target || 0}</span><span title="风化压力达到上限会导致旅程失败">风化压力 {goal?.weathering ?? state.shared.weathering_track ?? 0} / {goal?.weathering_limit ?? state.shared.weathering_limit ?? 5}</span><span title="剩余回合越少，越需要优先完成当前目标">剩余 {goal?.rounds_remaining ?? state.shared.max_rounds - state.shared.turn + 1} 回合</span></div></div></div><div className="header-actions">{connection !== '已连接' && <span className={`sync-state ${connection === '离线' ? 'offline' : ''}`} aria-live="polite"><span />{connection}</span>}</div></header>;
}
