import { useEffect, useState } from 'react';
import { CircleAlert, ChevronLeft, Library, Target, X } from 'lucide-react';
import type { Action, ActionType, ContentCard, ContentEvent, GameState, Meta, Site, Task } from '../../types/game';

type InspectorTab = 'task' | 'event' | 'market';
function domainName(meta: Meta, id: string) { return meta.domain_meta?.[id]?.short_name || id; }

export function SiteInspector({ state, meta, site, task, event, cards, legal, actionMode, collapsed, onCollapsedChange, onExplore }: { state: GameState; meta: Meta; site: Site; task?: Task; event?: ContentEvent; cards: Record<string, ContentCard>; legal: Action[]; actionMode: ActionType | null; collapsed: boolean; onCollapsedChange: (next: boolean) => void; onExplore: (id: string) => void }) {
  const eventPriority = Boolean(state.pending_choice || state.shared.current_event_id);
  const initial: InspectorTab = actionMode === 'explore' ? 'market' : eventPriority ? 'event' : 'task';
  const [tab, setTab] = useState(initial);
  useEffect(() => { setTab(actionMode === 'explore' ? 'market' : eventPriority ? 'event' : 'task'); }, [actionMode, eventPriority, site.id]);
  const action = legal.find(item => item.type === actionMode) || legal[0];
  if (collapsed) return <aside className="inspector-rail"><button className="inspector-expand" onClick={() => onCollapsedChange(false)} aria-label="展开地点检查器"><ChevronLeft size={18} /><span>地点</span></button></aside>;
  return <aside className="site-inspector" aria-label="地点检查器"><button className="inspector-collapse" onClick={() => onCollapsedChange(true)} aria-label="收起地点检查器"><X size={16} /></button><header className="inspector-summary"><span className="section-label">当前聚焦地点</span><h2>{site.name || site.id}</h2><div className="inspector-meta"><span>{site.kind === 'facility' ? '支持设施' : site.node_kind === 'event' ? '临时事件' : '遗产节点'}</span><span className={`site-status ${site.status}`}>{site.status === 'closed' ? '已关闭' : site.status === 'at_risk' ? '需修护' : '稳定'}</span></div><p>{site.summary || '尚未取得该地点的文化摘要。'}</p>{action && <div className="relevant-action"><span>当前相关行动</span><b>{action.label}</b><small>{action.cost || 0} AP</small></div>}</header><div className="inspector-tabs" role="tablist"><button role="tab" aria-selected={tab === 'task'} onClick={() => setTab('task')}><Target size={15} />任务</button><button role="tab" aria-selected={tab === 'event'} onClick={() => setTab('event')}><CircleAlert size={15} />事件</button><button role="tab" aria-selected={tab === 'market'} onClick={() => setTab('market')}><Library size={15} />市场</button></div><div className="inspector-content">{tab === 'task' && <section><h3>{task?.name || '等待探索解锁任务'}</h3><p>{task?.culture_explanation || '收集并贡献合适的文化证据，推动此处的研究任务。'}</p>{task && <><div className="inspector-progress"><span>证据槽</span><b>{task.contributed_cards.length} / {task.required_card_count}</b></div><div className="progress azure"><span style={{ width: `${task.required_card_count ? task.contributed_cards.length / task.required_card_count * 100 : 0}%` }} /></div><div className="domain-list">{task.required_domains.map(domain => <span key={domain}>{domainName(meta, domain)}</span>)}</div></>}</section>}{tab === 'event' && <section><div className="event-art"><img src={`/ui-assets/${event?.scene_asset || 'scene_frontier_pass.png'}`} alt="" /><div><h3>{event?.name || '本回合尚无待处理事件'}</h3><p>{event?.description || event?.summary || '结束回合后，世界事件会根据路线和节点状态结算。'}</p></div></div></section>}{tab === 'market' && <section className="market-tab"><h3>公开文化市场 <span>{state.market.length} 张</span></h3><div className="market-row">{state.market.map(id => { const item = cards[id]; const explore = legal.find(candidate => candidate.type === 'explore' && candidate.card_id === id); return <button key={id} className={`culture-card ${actionMode === 'explore' && explore ? 'selected' : ''}`} disabled={!explore} onClick={() => onExplore(id)}><img src={`/ui-assets/${item?.icon_asset || 'icon_card_scroll.png'}`} alt="" /><span><b>{item?.name || id}</b><small>{item?.domain ? domainName(meta, item.domain) : '文化证据'}</small></span><i>{explore ? `${explore.cost || 1} AP` : '不可选'}</i></button>; })}</div></section>}</div></aside>;
}
